### ISSUE TITLE
use `prefix` option as prefix to path, not only the db

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/pouchdb-adapter-fs#1]
This code currently creates `.fsdown/datamydb.json`, but I’d expect `data/mydb.json` as the leveldb adapter does it.

``` js
var PouchDB = require('pouchdb-core')
  .plugin(require('pouchdb-adapter-fs'))
  .defaults({
    prefix: 'data/'
  })

new PouchDB('mydb')
```

Would you agree? 

For Hoodie we need the folder where the databases are stored to be configurable.
I’d suggest that we default to `.fsdown/` unless the `prefix` option is set.

**Comment by nolanlawson** [comment]
This sounds reasonable to me. I'm actually also open to just removing `the whole .fsdown` prefix and just pushing a 2.0.0 version. This project is young and I'm sure not many people are using it.

**Comment by gr2m** [comment]
>  I'm actually also open to just removing the whole .fsdown prefix 

Agree 👍 I think it’s best to match the leveldb adapter’s behavior. I’ll work on a PR, thanks Nolan :)

**Comment by gr2m** [comment]
Can you invite me to this repository, so we can collab on the PR if needed?

**Comment by nolanlawson** [comment]
sure thing!

**Comment by gr2m** [comment]
sorry can you add me to https://github.com/nolanlawson/fsdown, too? Sorry for pinging you on slack, too I got distracted shortly and forgot I already pinged you on GitHub

**Comment by gr2m** [comment]
shipped in [v2](https://github.com/nolanlawson/pouchdb-adapter-fs/releases/tag/v2.0.0)
