### ISSUE TITLE
enable Greenkeeper

### ISSUE THREAD

**Issue by gr2m** [nolanlawson/pouchdb-adapter-fs#3]
I tried to do it myself but I don’t have admin access to the repository

**Comment by gr2m** [comment]
and could you please active this repo at travis, too? Or make me an admin?

**Comment by nolanlawson** [comment]
Activated! Not sure how to make you an admin, though. You mean in Github or in Travis or...?

**Comment by nolanlawson** [comment]
GK enabled, Travis enabled
